In [1]:
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [2]:
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
np.random.randint(1, 101, 20)

array([86, 68, 86, 40, 47, 31, 75,  2,  5, 72, 92, 14, 26, 36, 46, 35, 11,
       93, 83, 23])

In [6]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [7]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
arr = np.random.randint(1,100,20)
arr > 50

array([ True, False,  True, False,  True, False,  True, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False,  True])

In [9]:
np.empty(10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [14]:
arr[arr % 2 == 0]

array([84, 18, 66, 16, 44, 78,  6,  4])

In [26]:
arr2d = np.arange(12).reshape(3,4)
print(arr2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
arr2d[1]

array([4, 5, 6, 7])

In [28]:
arr[arr < 0] = 0

In [29]:
arr[arr > arr.mean()]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [30]:
arr[1::2]

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [31]:
arr[3] = 99

In [32]:
arr2d[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [33]:
arr.T

array([10, 11, 12, 99, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.repeat(arr, 2)

array([10, 10, 11, 11, 12, 12, 99, 99, 14, 14, 15, 15, 16, 16, 17, 17, 18,
       18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26,
       27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35,
       35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42, 42, 43, 43,
       44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49])

In [39]:
np.tile(arr, 2)

array([10, 11, 12, 99, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 10, 11, 12, 99, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
arr[[0,1]] = arr[[1,0]]

In [42]:
np.unique(arr)

array([10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 99])

In [43]:
arr**2

array([ 121,  100,  144, 9801,  196,  225,  256,  289,  324,  361,  400,
        441,  484,  529,  576,  625,  676,  729,  784,  841,  900,  961,
       1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764,
       1849, 1936, 2025, 2116, 2209, 2304, 2401])

In [44]:
np.sqrt(arr)

array([3.31662479, 3.16227766, 3.46410162, 9.94987437, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [45]:
(arr - arr.min()) / (arr.max() - arr.min())

array([0.01123596, 0.        , 0.02247191, 1.        , 0.04494382,
       0.05617978, 0.06741573, 0.07865169, 0.08988764, 0.1011236 ,
       0.11235955, 0.12359551, 0.13483146, 0.14606742, 0.15730337,
       0.16853933, 0.17977528, 0.19101124, 0.20224719, 0.21348315,
       0.2247191 , 0.23595506, 0.24719101, 0.25842697, 0.26966292,
       0.28089888, 0.29213483, 0.30337079, 0.31460674, 0.3258427 ,
       0.33707865, 0.34831461, 0.35955056, 0.37078652, 0.38202247,
       0.39325843, 0.40449438, 0.41573034, 0.42696629, 0.43820225])

In [46]:
np.dot(a, b)

np.int64(32)

In [47]:
a * b

array([ 4, 10, 18])

In [48]:
np.count_nonzero(arr)

np.int64(40)

In [49]:
np.round(arr, 2)

array([11, 10, 12, 99, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [50]:
np.nan_to_num(arr)

array([11, 10, 12, 99, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [51]:
np.argmax(arr)

np.int64(3)

In [52]:
np.sort(arr)

array([10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 99])

In [53]:
arr2d[arr2d[:,1].argsort()]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.unique(arr, return_counts=True)

(array([10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
        45, 46, 47, 48, 49, 99]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [55]:
np.cumsum(arr)

array([  11,   21,   33,  132,  146,  161,  177,  194,  212,  231,  251,
        272,  294,  317,  341,  366,  392,  419,  447,  476,  506,  537,
        569,  602,  636,  671,  707,  744,  782,  821,  861,  902,  944,
        987, 1031, 1076, 1122, 1169, 1217, 1266])

In [56]:
np.cumprod(arr)

array([                  11,                  110,                 1320,
                     130680,              1829520,             27442800,
                  439084800,           7464441600,         134359948800,
              2552839027200,       51056780544000,     1072192391424000,
          23588232611328000,   542529350060544000, -5426039672256495616,
       -6523783290445529088, -3597668888197791744, -4903339612792619008,
       -8166300642226470912,  2984954333656514560, -2685090358852321280,
        8995919244125798400, -7278489367327277056,  -382476163575971840,
        5442554512126509056,  6021967187332300800, -4570110140551790592,
       -3073378537030287360, -6107919964893609984,  1598794327373381632,
        8611540873806610432,  2585038425589547008, -2108850567496335360,
        1553145966205337600, -5448553781803352064, -5377247222926671872,
       -7545699296402735104, -4159729530447069184,  3247167349345746944,
       -6909496545444364288])

In [58]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

In [59]:
(arr >= 20) & (arr <= 40)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False])

In [60]:
arr[1:-1] = (arr[:-2] + arr[2:]) / 2

In [61]:
np.sort(arr2d, axis=0)[-3:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
(arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:])

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])