IMPLEMENT AND,OR,NOT AND XOR GATE BY USING ANNS, USE SCIKIT LEARN FOR IT

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

In [4]:
# AND GATE
X_and =np.array([[0,0],[0,1],[1,0],[1,1]])
Y_and=np.array([0,0,0,1])

model_and = MLPClassifier(hidden_layer_sizes=(2,), max_iter=1000)
model_and.fit(X_and, Y_and)

print("AND Gate:")
print(model_and.predict(X_and))

AND Gate:
[0 0 0 0]


/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [10]:
X_or = np.array([[0,0],[0,1],[1,0],[1,1]])
y_or = np.array([0,1,1,1])
model_or = MLPClassifier(hidden_layer_sizes=(2,), max_iter=5000)
model_or.fit(X_or, y_or)

print("OR Gate:")
print(model_or.predict(X_or))

OR Gate:
[0 1 1 1]


In [7]:
X_xor = np.array([[0,0],[0,1],[1,0],[1,1]])
y_xor = np.array([0,1,1,0])
model_xor = MLPClassifier(hidden_layer_sizes=(4,), max_iter=2000)
model_xor.fit(X_xor, y_xor)

print("XOR Gate:")
print(model_xor.predict(X_xor))

XOR Gate:
[0 1 1 0]


/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
X_not = np.array([[0],[1]])
y_not = np.array([1,0])
model_not = MLPClassifier(hidden_layer_sizes=(2,), max_iter=1000)
model_not.fit(X_not, y_not)
print("NOT Gate:")
print(model_not.predict(X_not))

NOT Gate:
[1 0]


/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
